name: country_icons

description: A flutter package with many country flag icons that you can use via the Image.asset method
homepage: https://github.com/bytepark/country_icons
repository: https://github.com/bytepark/country_icons
issue_tracker: https://github.com/bytepark/country_icons/issues
version: 3.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - icons/flags/png100px/
    - icons/flags/png250px/
    - icons/flags/png1000px/
    - icons/flags/svg/

topics:
  - assets
  - icons
  - ui